# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5c1d2854603a4d6ba0ffc9177a85972673376f90c4d66fc156eeeeb225e4b60f991715b2f8714ab296ab28b41affee20ed1aaf592ee9fd3144bab637b434939

test:
  secret_key_base: dd1aab94e51099dad5d9697337aad63af54ef3ba8c18ffe9e6967a0b06c3bded10039ce4c74d96f04153af95c7c36810b1f7a9db0adf0aba273ec36a428a26cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
